apiVersion: v1
kind: Service
metadata:
  name: python-web-app
spec:
  selector:
    app: python-web-app #this should match the pod label to perform the service discovery
  type: ClusterIP
  ports:
  - name: python-web-app
    protocol: TCP
    port: 80
    targetPort: 5000
