name: EKS-PYTHON-EKS

on:
  push:
    branches: [ "main" ]

jobs:
  Templates:
    uses: arjunpt/argo-eks/.github/workflows/cicd.yml@main
    with:
      python-version: "3.10"
      requirements-path: "src/requirements.txt"
      test-path: "src/test/test.py"
      dockerfile-path: "Dockerfile"
      ecr-repo-name: "python"
      ECR_REGISTRY: "445567111188.dkr.ecr.us-east-2.amazonaws.com"
      IMAGE_NAME: "python"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      KUBE_CONFIG_PROD: ${{ secrets.KUBE_CONFIG_PROD }}
      TOKEN: ${{ secrets.TOKEN }}
